# Generated by Django 6.0 on 2025-12-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_comment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/'),
        ),
    ]
